# Generated by Django 2.1.7 on 2019-10-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django-data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='name',
            new_name='testname',
        ),
    ]
