# Generated by Django 2.1.7 on 2019-10-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django-data', '0002_auto_20191021_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.TextField()),
                ('primary_token', models.TextField(blank=True, null=True)),
                ('secondary_token', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('verified', models.BooleanField()),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
